### ISSUE TITLE
Failed to complile assets

### ISSUE THREAD

**Issue by fachattiamine** [vanilophp/framework#113]
ERROR in ./vendor/konekt/appshell/src/resources/assets/sass/appshell.sass
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Only 4 arguments allowed, but 5 were passed.
    ┌──> vendor\konekt\appshell\src\resources\assets\sass\appshell\_buttons.sass
2   │     +button-size(.15rem, .25rem, $font-size-xs, 1.1em, .1rem)
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ invocation
    ╵
    ┌──> node_modules\bootstrap\scss\mixins\_buttons.scss
127 │ @mixin button-size($padding-y, $padding-x, $font-size, $border-radius) {
    │        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ declaration
    ╵
  vendor\konekt\appshell\src\resources\assets\sass\appshell\_buttons.sass 2:5  button-size()
  vendor\konekt\appshell\src\resources\assets\sass\appshell\_buttons.sass 2:5  @import
  vendor\konekt\appshell\src\resources\assets\sass\appshell.sass 13:9          root stylesheet
    at processResult (D:\Projects\Websites\vaniloapp\node_modules\webpack\lib\NormalModule.js:751:19)
    at D:\Projects\Websites\vaniloapp\node_modules\webpack\lib\NormalModule.js:853:5
    at D:\Projects\Websites\vaniloapp\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at D:\Projects\Websites\vaniloapp\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (D:\Projects\Websites\vaniloapp\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at D:\Projects\Websites\vaniloapp\node_modules\sass-loader\dist\index.js:54:7
    at Function.call$2 (D:\Projects\Websites\vaniloapp\node_modules\sass\sass.dart.js:96930:16)
    at render_closure1.call$2 (D:\Projects\Websites\vaniloapp\node_modules\sass\sass.dart.js:82802:12)
    at _RootZone.runBinary$3$3 (D:\Projects\Websites\vaniloapp\node_modules\sass\sass.dart.js:28524:18)
    at _FutureListener.handleError$1 (D:\Projects\Websites\vaniloapp\node_modules\sass\sass.dart.js:27046:21)

**Comment by fulopattila122** [comment]
You need Bootstrap 4 (preferably 4.5 or 4.6). The admin theme isn't compatible with Bootstrap 5.x

**Comment by fulopattila122** [comment]
Did it solve your issue?
